
[dependencies]
  "github.com/aws/aws-sdk-go" = "v1.44.28"
  "github.com/aws/smithy-go" = "v1.22.0"
  "github.com/jmespath/go-jmespath" = "v0.4.0"
  "github.com/aws/aws-sdk-go-v2/internal/configsources" = "v1.3.21"
  "github.com/aws/aws-sdk-go-v2/internal/endpoints/v2" = "v2.6.21"

[modules]

  [modules."."]
    metadata_package = "aws"
